### PR TITLE
Add option to expire notifications by time

### PR DESCRIPTION
**Pull request by erasaur**
Also had to change the timestamps to Date type, since MongoDB doesn't seem to support expiring for the epoch number format.

### CODE REVIEW

**Comment by dohomi** [comment]
looks good to me but don't have the time to validate

**Comment by Kestanous** [comment]
Just eyeballing it but it looks good to me too. I expect to resume Herald work in the next two weeks or so and can validate then. Merge as you feel comfortable.

**Comment by erasaur** [comment]
It's probably not an ideal solution, since we probably want to take into consideration whether notifications are read, how many notifications a user has already, etc (actually in my case it suits my needs just fine). But take it as a quick solution before we go about refactoring, which might last a while.

**Comment by dohomi** [comment]
Hey guy, for me in my usecase I would never have notifications expire after a while. My notifications will be present because they meant to notify on received messages or comments. I won't have the time to proof this PR soon. Sorry for that

**Comment by erasaur** [comment]
No problem. Just a note: specifying expire time of 0 would mean the notifications never expire. Nothing should break except for the minor change of the timestamp format (Date().getTime() -> Date())

**Comment by Kestanous** [comment]
@erasaur thats what I was seeing. Good call on `0 == none`. The code does not rely on timestamps right now, right? The only thing that currently uses timestamps would be the queue.

**Comment by erasaur** [comment]
I think even the queue is managed by a separate queueTimer, right? One odd behavior that I expect is that old notifications (with the incorrect timestamp format) won't be expired.

**Comment by Kestanous** [comment]
A shame but makes sense. Given that its not an option right now no users will be bothered by it.

**Comment by erasaur** [comment]
Since this is working for me, I'll go ahead and merge this PR and we can make amendments in the future.

**Comment by Kestanous** [comment]
Published for all packages

**Pull request merged**
