### PR TITLE
removed console.log

### PR DESCRIPTION
**Pull request by SachaG**
It just doesn't seem that useful to show this message every time your app starts?

### CODE REVIEW

**Comment by dohomi** [comment]
thanks @SachaG

**Comment by Kestanous** [comment]
Agreed, that was excessive. Thanks!

**Comment by SachaG** [comment]
Is this published yet? I have version 1.1.3 but I'm still seeing the message?

**Comment by Kestanous** [comment]
Sorry @SachaG I have published it yet, there are some changes in master that I have not tested yet. I am spending this week getting back to Herald. The original app that used Herald has stalled and thus I am not updating herald regularly enough. My current project will begin using Herald over the next few weeks so I should be able to get back on the ball.

In the mean time you could pull in master but I can't promise it will not break telescope.

**Comment by SachaG** [comment]
No worries, I can wait :)

**Comment by Kestanous** [comment]
@SachaG published for all packages :) thanks for the wait!

**Comment by SachaG** [comment]
Awesome :)

**Pull request merged**
