### PR TITLE
Route detection fix. Iron router renamed path to url.

### LINKED ISSUE #51: Route Detection does not work
On iron:router@1.0.7.

[this.path](https://github.com/Meteor-Reaction/Herald/blob/master/client/startup.js#L19) is undefined.

### PR DESCRIPTION
**Pull request by delgermurun**
Route detection fix. Iron router renamed path to url.

Closes #51

### CODE REVIEW

**Comment by erasaur** [comment]
Thanks @delgermurun. I'm not sure we want the entire url though, but something along the lines of `this.route._path`.

**Comment by Kestanous** [comment]
Hmm agreed. We want to let users define `/my/route` and have it work. 

But that brings up good point, what urls are valid? We could get 'http://domain/my/route`, 'https://domain/my/route`, 'domain/my/route`, '/my/route`, and 'my/route`. They should all be valid, except for the last one but we can assume the dev meant `/my/route`. 

Thoughts @Meteor-Reaction/Herald?

**Comment by erasaur** [comment]
Maybe we can leverage IR's existing utilities, i.e create an Iron url instance with the url and use the built in normalize function (which turns url or path into a path with a leading slash). Then we only need to consider one type of those you listed. 

See [here](https://github.com/EventedMind/iron-url/blob/master/lib/url.js) for reference.

**Comment by Kestanous** [comment]
@erasaur I like that idea. `Url.parse` looks promising and we can add it by adding `iron:url` as a package dependancy.

**Comment by dohomi** [comment]
Please keep in mind of your change, that not all users have yet switched to the new 1.x api of iron:router. So we should implement an option to disable the iron:router functionality where users need to implement their own recognition function for the routing.

**Comment by delgermurun** [comment]
`console.log(this)` tells me that `url`'s value is whole URL (with domain) when I directly go to url (not clicking anchor). But `console.log(this.url)` logs absolute path (without domain). I don't know why it is.

I set herald's url value using `Router.routes[<route_name>].path` function. It gives absolute path (/my/route). I think it is right url. And this fix works for me.

**Comment by erasaur** [comment]
Sorry for the late reply. I'll have a look at this later today.

**Comment by erasaur** [comment]
Oddly enough, it looks like @delgermurun's observations are correct. If anybody knows why it behaves this way, please chime in. Anyway, it looks like this solves the problem, so I'll go ahead and merge this.

**Comment by delgermurun** [comment]
@erasaur Yeah it's odd. If someone figure this out. Tell me please :D

**Comment by delgermurun** [comment]
@erasaur when will it release?

**Comment by Kestanous** [comment]
@delgermurun Thats on me. I will try to update today. 

FYI all I have been working on getting tests in https://github.com/Meteor-Reaction/Herald-Example. In the future I will be more confident on publishing changes faster when I know the tests are passing.

**Comment by Kestanous** [comment]
@delgermurun updated for all packages

**Pull request merged**
